# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:20 AS builder

WORKDIR /app

# Copy package.json and pnpm-lock.yaml to the working directory
COPY package.json pnpm-lock.yaml ./

# Install pnpm
RUN npm install -g pnpm

# Install dependencies
RUN pnpm install

# Copy the rest of the application code
COPY . .

# Build the project
RUN pnpm build

FROM node:20-slim

WORKDIR /app

# Copy the built application from the builder image
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/pnpm-lock.yaml /app/

# Install only production dependencies
RUN npm install -g pnpm && pnpm install --prod

# The environment variable required by the server
ENV PERPLEXITY_API_KEY=your-perplexity-api-key

# Set the command to run the server
CMD ["node", "dist/index.js"]